Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelWebApi.Models
{
    public class Booking
    {
        public string BookingId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int RoomId { get; set; }
        public string UserId { get; set; }
        public int NumberOfPersons { get; set; }
        public bool BookingApproved { get; set; }
        public virtual Room Room { get; set; }


    }
}

Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelWebApi.Models
{
    public class Branch
    {
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string BranchImagePath { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}

Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelWebApi.Models
{
    public class Room
    {
        public int RoomId { get; set; }
        public string Description { get; set; }
        public decimal PriceForNight { get; set; }
        public float Rate { get; set; }
        public RoomType RoomType { get; set; }
        public int NumberOfPersons { get; set; }
        //public HttpPostedFileBase RoomImageFile { get; set; }
        public int BranchId { get; set; }
        public string RoomImagePath { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Branch Branch { get; set; }
    }
    public enum RoomType
    {
        Single,
        Double,
        Suite
    }
}

Controllers/BookingCommunicatorController.cs
using HotelAppInterfaceBackend.Services;
using HotelWebApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace HotelAppInterfaceBackend.Controllers
{
    public class BookingCommunicatorController : Controller
    {
        private readonly IService<Booking> BookingService;
        public BookingCommunicatorController(IService<Booking> _service)
        {
            BookingService = _service;
        }
        // GET: BookingCommunicator
        public ActionResult Index()
        {
            var BookingList = BookingService.GetAllItems();
            if (BookingList == null)
            {
                BookingList = new List<Booking>();
            }
            return View(BookingList);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelAppInterfaceBackend.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/RoomsCommunicatorController.cs
using HotelAppInterfaceBackend.Services;
using HotelWebApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace HotelAppInterfaceBackend.Controllers
{
    public class RoomsCommunicatorController : Controller
    {
        private readonly IService<Room> RoomService;
        private readonly IService<Branch> BranchService;
        public RoomsCommunicatorController(IService<Room> _service , IService<Branch> _BService)
        {
            RoomService = _service;
            BranchService = _BService;
        }
        // GET: RoomsCommunicator
        public ActionResult Index()
        {
            var roomList = RoomService.GetAllItems();
            if(roomList == null)
            {
                roomList = new List<Room>();
            }
            return View(roomList);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.list = new SelectList(BranchService.GetAllItems(), "BranchId", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Room room)
        {
            if (!ModelState.IsValid)
            {
                return View(room);
            }
            bool Succeded = RoomService.AddItem(room);
            if (Succeded)
            {
                return RedirectToAction("Index");
            }
            ViewBag.list = new SelectList(BranchService.GetAllItems(), "BranchId", "Name");
            return View();
        }
    }
}

Views/BookingCommunicator/Index.cshtml
@model IEnumerable<HotelWebApi.Models.Booking>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPersons)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookingApproved)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfPersons)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookingApproved)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookingId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookingId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookingId })
        </td>
    </tr>
}

</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/RoomsCommunicator/Create.cshtml
@model HotelWebApi.Models.Room

@{
    ViewBag.Title = "AddRoom";
}

<h2>AddRoom</h2>

<form  ></form>
@using (Html.BeginForm("Create","RoomsCommunicator",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Room</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PriceForNight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PriceForNight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PriceForNight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberOfPersons, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumberOfPersons, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumberOfPersons, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BranchId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.BranchId, (SelectList)ViewBag.list, new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.RoomType, htmlAttributes : new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        <label id="RoomImg" class="control-label col-md-2">Room Image</label>
        <div class="col-md-10">
            <input type="file" id="RoomImg" name="RoomImageFile" class="form-control" />
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/RoomsCommunicator/Index.cshtml
@model IEnumerable<HotelWebApi.Models.Room>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceForNight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPersons)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Branch.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PriceForNight)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Rate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NumberOfPersons)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Branch.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RoomType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RoomImagePath)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.RoomId }) |
        @Html.ActionLink("Details", "Details", new { id = item.RoomId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.RoomId })
    </td>
</tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Rooms", "Index", "RoomsCommunicator")</li>
                    <li>@Html.ActionLink("Bookings", "Index", "BookingCommunicator")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>